### ISSUE TITLE
有几个版权相关的问题想要确认一下

### ISSUE THREAD

**Issue by LondonX** [gwsice/buddhism#33]
感谢作者能收集并维护这么多经书。
有几个问题想要确认一下

1. 请问这些经书有没有版权的说法。
2. 如果我想基于您的数据集做开发需要遵循哪种开源协议。
3. 如果我部分引用了您的数据是否需要注明出处。

万分感谢

**Comment by wenshengguo** [comment]
Hi LondonX，

非常感谢您的鼓励和支持。

根据我个人的理解，我认为传世的经论是不存在版权问题的。我按照作者及译者去世后50年为期简单整理了一下著作权可能出问题的作者供您参考：

1. 《大设计》，霍金（2018）

2. 《狂密与真密》，萧平实

3. 《土观宗派源流》，刘立千（2008）

4. 《菩提道次第广论》、《入中论讲记》、《密宗道次第广论》、《释量论》、《中观四百论》，法尊法师（1980）

5. 《量理宝藏论》，明性法师

6. 《大圆满心性休息大车疏》、《入二谛论》、《释迦牟尼佛广传·白莲花论》、《百业经》、《现观庄严论》、《解义慧剑》、《定解宝灯论》、《般若摄颂》，索达吉堪布

7. 《三自性论》，韩镜清（2003）

8. 《辨法法性论》、《赞法界颂》，谈锡永

9. 印顺法师（2005）

10. 《大藏会阅》，会性法师（2010）

11. 《清净道论》，叶均（1985）

12. 《扎莫囊敦》，陈健民（1987）

13. 《西藏度亡经》，徐进夫（1990）

14. 《一切密续之根本幻化网秘密藏真实决定根本续》，沈卫荣

相关的论文注明作者和出处后应该没有版权问题了。

我个人坚信促进佛法的广泛传播应该我们这些有佛教信仰的人在现代社会的一个重要工作。因此对于您的第二个问题，我觉得必须是MIT协议。

创建并维护这个开源项目的目的是希望除我以外能有更多的人加入到这一佛学著作的收集、整理、校对和注释工作中来，并为网络讨论提供一个相对规范的引用平台。因此，我衷心希望您在引用过程中帮助推广一下。

万分感谢您的肯定。人生苦短，真心希望能有更多的同修能和我一起把这件事做下去。
